### ISSUE TITLE
Bug Report: Import File Isn't Working Anymore

### ISSUE THREAD

**Issue by bigmutty** [Hizoul/optikey-boardlayout#5]
When I try to import a file, I get this exception:

boardlayout.js:413 Uncaught Error: Unexpected close tag
Line: 97
Column: 17
Char: >
    at j (boardlayout.js:413)
    at E (boardlayout.js:413)
    at C (boardlayout.js:413)
    at i.write (boardlayout.js:412)
    at Object.e.exports [as xml2js] (boardlayout.js:338)
    at Object.t.default (boardlayout.js:61)
    at FileReader.S.t.onloadend (boardlayout.js:412)
j @ boardlayout.js:413
E @ boardlayout.js:413
C @ boardlayout.js:413
write @ boardlayout.js:412
e.exports @ boardlayout.js:338
t.default @ boardlayout.js:61
S.t.onloadend @ boardlayout.js:412
FileReader (async)
S @ boardlayout.js:412
(anonymous) @ boardlayout.js:415
Promise.then (async)
(anonymous) @ boardlayout.js:415
(anonymous) @ boardlayout.js:415
(anonymous) @ boardlayout.js:415
s @ boardlayout.js:379
p @ boardlayout.js:379
(anonymous) @ boardlayout.js:379
g @ boardlayout.js:379
ot @ boardlayout.js:379
at @ boardlayout.js:379
st @ boardlayout.js:379
pt @ boardlayout.js:379
A @ boardlayout.js:379
z @ boardlayout.js:379
Xt @ boardlayout.js:379
Qt @ boardlayout.js:379
t.unstable_runWithPriority @ boardlayout.js:387
Wa @ boardlayout.js:379
C @ boardlayout.js:379
Gt @ boardlayout.js:379
boardlayout.js:61 Uncaught TypeError: t is not iterable
    at Object.t.default (boardlayout.js:61)
    at FileReader.S.t.onloadend (boardlayout.js:412)

This feature was working 2 days ago. Here's the file I was trying to import, but I tried importing other dynamic keyboards to no avail.

`<Keyboard>
  <Name>Vertical QWERTY Keyboard</Name>
  <Height>100%</Height>
  <SymbolMargin>1</SymbolMargin>
  <BorderThickness>0,0,0,0</BorderThickness>
  <DockSize>Full</DockSize>
  <Position>Left</Position>
  <Width>20%</Width>
  <HorizontalOffset>0</HorizontalOffset>
  <VerticalOffset>0</VerticalOffset>
  <BackgroundColor>Transparent</BackgroundColor>
  <BorderColor>Transparent</BorderColor>
  <WindowState>Docked</WindowState>
  <Grid>
    <Rows>18</Rows>
    <Cols>4</Cols>
  </Grid>
  <KeyGroup Name="Function Keys" BackgroundColor="dark gray"/>
  <KeyGroup Name="Mouse Function Keys" BackgroundColor=" gray"/>
  <Content>
    <DynamicKey Row="6" Col="0">
      <Text></Text>
      <Label>0</Label>
      <ShiftDownLabel>)</ShiftDownLabel>
      <Text>0</Text>
    </DynamicKey>
    <DynamicKey Row="6" Col="1">
      <Text></Text>
      <Label>p</Label>
      <ShiftDownLabel>P</ShiftDownLabel>
      <Text>p</Text>
    </DynamicKey>
    <DynamicKey Row="6" Col="2">
      <Text></Text>
      <Label>l</Label>
      <ShiftDownLabel>L</ShiftDownLabel>
      <Text>l</Text>
    </DynamicKey>
    <DynamicKey Row="6" Col="3">
      <Text></Text>
      <Label>.</Label>
      <ShiftDownLabel>&gt;</ShiftDownLabel>
      <Text>.</Text>
    </DynamicKey>
    <DynamicKey Row="7" Col="0">
      <Text></Text>
      <Label>9</Label>
      <ShiftDownLabel>(</ShiftDownLabel>
      <Text>9</Text>
    </DynamicKey>
    <DynamicKey Row="7" Col="1">
      <Text></Text>
      <Label>o</Label>
      <ShiftDownLabel>O</ShiftDownLabel>
      <Text>o</Text>
    </DynamicKey>
    <DynamicKey Row="7" Col="2">
      <Text></Text>
      <Label>k</Label>
      <ShiftDownLabel>K</ShiftDownLabel>
      <Text>k</Text>
    </DynamicKey>
    <DynamicKey Row="7" Col="3">
      <Text></Text>
      <Label>,</Label>
      <ShiftDownLabel>&lt;</ShiftDownLabel>
      <Text>,</Text>
    </DynamicKey>
    <DynamicKey Row="8" Col="0">
      <Text></Text>
      <Label>8</Label>
      <ShiftDownLabel>*</ShiftDownLabel>
      <Text>8</Text>
    </DynamicKey>
    <DynamicKey Row="8" Col="1">
      <Text></Text>
      <Label>i</Label>
      <ShiftDownLabel>I</ShiftDownLabel>
      <Text>i</Text>
    </DynamicKey>
    <DynamicKey Row="8" Col="2">
      <Text></Text>
      <Label>j</Label>
      <ShiftDownLabel>J</ShiftDownLabel>
      <Text>j</Text>
    </DynamicKey>
    <DynamicKey Row="8" Col="3">
      <Text></Text>
      <Label>m</Label>
      <ShiftDownLabel>M</ShiftDownLabel>
      <Text>m</Text>
    </DynamicKey>
    <DynamicKey Row="9" Col="0">
      <Text></Text>
      <Label>7</Label>
      <ShiftDownLabel>&</ShiftDownLabel>
      <Text>7</Text>
    </DynamicKey>
    <DynamicKey Row="9" Col="1">
      <Text></Text>
      <Label>u</Label>
      <ShiftDownLabel>U</ShiftDownLabel>
      <Text>u</Text>
    </DynamicKey>
    <DynamicKey Row="9" Col="2">
      <Text></Text>
      <Label>h</Label>
      <ShiftDownLabel>H</ShiftDownLabel>
      <Text>h</Text>
    </DynamicKey>
    <DynamicKey Row="9" Col="3">
      <Text></Text>
      <Label>n</Label>
      <ShiftDownLabel>N</ShiftDownLabel>
      <Text>n</Text>
    </DynamicKey>
    <DynamicKey Row="10" Col="0">
      <Text></Text>
      <Label>6</Label>
      <ShiftDownLabel>^</ShiftDownLabel>
      <Text>6</Text>
    </DynamicKey>
    <DynamicKey Row="10" Col="1">
      <Text></Text>
      <Label>y</Label>
      <ShiftDownLabel>Y</ShiftDownLabel>
      <Text>y</Text>
    </DynamicKey>
    <DynamicKey Row="10" Col="2">
      <Text></Text>
      <Label>g</Label>
      <ShiftDownLabel>G</ShiftDownLabel>
      <Text>g</Text>
    </DynamicKey>
    <DynamicKey Row="10" Col="3">
      <Text></Text>
      <Label>b</Label>
      <ShiftDownLabel>B</ShiftDownLabel>
      <Text>b</Text>
    </DynamicKey>
    <DynamicKey Row="11" Col="0">
      <Text></Text>
      <Label>5</Label>
      <ShiftDownLabel>%</ShiftDownLabel>
      <Text>5</Text>
    </DynamicKey>
    <DynamicKey Row="11" Col="1">
      <Text></Text>
      <Label>t</Label>
      <ShiftDownLabel>T</ShiftDownLabel>
      <Text>t</Text>
    </DynamicKey>
    <DynamicKey Row="11" Col="2">
      <Text></Text>
      <Label>f</Label>
      <ShiftDownLabel>F</ShiftDownLabel>
      <Text>f</Text>
    </DynamicKey>
    <DynamicKey Row="11" Col="3">
      <ShiftDownLabel>V</ShiftDownLabel>
      <Label>v</Label>
      <Text>undefined</Text>
      <Text>v</Text>
    </DynamicKey>
    <DynamicKey Row="12" Col="0">
      <ShiftDownLabel>$</ShiftDownLabel>
      <Label>4</Label>
      <Text>undefined</Text>
      <Text>4</Text>
    </DynamicKey>
    <DynamicKey Row="12" Col="1">
      <ShiftDownLabel>R</ShiftDownLabel>
      <Label>r</Label>
      <Text>undefined</Text>
      <Text>r</Text>
    </DynamicKey>
    <DynamicKey Row="12" Col="2">
      <ShiftDownLabel>D</ShiftDownLabel>
      <Label>d</Label>
      <Text>undefined</Text>
      <Text>d</Text>
    </DynamicKey>
    <DynamicKey Row="12" Col="3">
      <ShiftDownLabel>C</ShiftDownLabel>
      <Label>c</Label>
      <Text>undefined</Text>
      <Text>c</Text>
    </DynamicKey>
    <DynamicKey Row="13" Col="0">
      <ShiftDownLabel>#</ShiftDownLabel>
      <Label>3</Label>
      <Text>undefined</Text>
      <Text>3</Text>
    </DynamicKey>
    <DynamicKey Row="13" Col="1">
      <ShiftDownLabel>E</ShiftDownLabel>
      <Label>e</Label>
      <Text>undefined</Text>
      <Text>e</Text>
    </DynamicKey>
    <DynamicKey Row="13" Col="2">
      <ShiftDownLabel>S</ShiftDownLabel>
      <Label>s</Label>
      <Text>undefined</Text>
      <Text>s</Text>
    </DynamicKey>
    <DynamicKey Row="13" Col="3">
      <ShiftDownLabel>X</ShiftDownLabel>
      <Label>x</Label>
      <Text>undefined</Text>
      <Text>x</Text>
    </DynamicKey>
    <DynamicKey Row="14" Col="0">
      <ShiftDownLabel>@</ShiftDownLabel>
      <Label>2</Label>
      <Text>undefined</Text>
      <Text>2</Text>
    </DynamicKey>
    <DynamicKey Row="14" Col="1">
      <ShiftDownLabel>W</ShiftDownLabel>
      <Label>w</Label>
      <Text>undefined</Text>
      <Text>w</Text>
    </DynamicKey>
    <DynamicKey Row="14" Col="2">
      <ShiftDownLabel>A</ShiftDownLabel>
      <Label>a</Label>
      <Text>undefined</Text>
      <Text>a</Text>
    </DynamicKey>
    <DynamicKey Row="14" Col="3">
      <ShiftDownLabel>Z</ShiftDownLabel>
      <Label>z</Label>
      <Text>undefined</Text>
      <Text>z</Text>
    </DynamicKey>
    <DynamicKey Row="15" Col="0">
      <ShiftDownLabel>!</ShiftDownLabel>
      <Label>1</Label>
      <Text>undefined</Text>
      <Text>1</Text>
    </DynamicKey>
    <DynamicKey Row="15" Col="1">
      <ShiftDownLabel>Q</ShiftDownLabel>
      <Label>q</Label>
      <Text>undefined</Text>
      <Text>q</Text>
    </DynamicKey>
    <DynamicKey Row="15" Col="2">
      <Symbol>WinIcon</Symbol>
      <Text>undefined</Text>
      <Action>LeftWin</Action>
    </DynamicKey>
    <DynamicKey Row="15" Col="3">
      <Label>CTRL</Label>
      <Text>undefined</Text>
      <Action>LeftCtrl</Action>
    </DynamicKey>
    <DynamicKey Row="16" Col="0">
      <ShiftDownLabel>~</ShiftDownLabel>
      <Label>`</Label>
      <Text>undefined</Text>
      <Text>`</Text>
    </DynamicKey>
    <DynamicKey Row="16" Col="1">
      <Symbol>TabIcon</Symbol>
      <Text>&#9;</Text>
      <Text>undefined</Text>
      <Text>undefined</Text>
      <Text>undefined</Text>
    </DynamicKey>
    <DynamicKey Row="16" Col="2">
      <Symbol>ShiftIcon</Symbol>
      <Text>undefined</Text>
      <Action>LeftShift</Action>
    </DynamicKey>
    <DynamicKey Row="16" Col="3">
      <Label>ALT</Label>
      <Text>undefined</Text>
      <Action>LeftAlt</Action>
    </DynamicKey>
    <DynamicKey Row="17" Col="0">
      <Symbol>MouseIcon</Symbol>
      <Text>undefined</Text>
      <Action>MouseKeyboard</Action>
    </DynamicKey>
    <DynamicKey Row="17" Col="1">
      <Symbol>MouseMagnifierIcon</Symbol>
      <Text>undefined</Text>
      <Action>MouseMagnifier</Action>
    </DynamicKey>
    <DynamicKey Row="17" Col="2">
      <Symbol>MouseLeftClickIcon</Symbol>
      <Text>undefined</Text>
      <Action>MouseMoveAndLeftClick</Action>
    </DynamicKey>
    <DynamicKey Row="17" Col="3">
      <Symbol>MouseLeftDoubleClickIcon</Symbol>
      <Text>undefined</Text>
      <Action>MouseMoveAndLeftClick</Action>
    </DynamicKey>
  </Content>
</Keyboard>`

**Comment by Hizoul** [comment]
That's weird the parsing code hasn't changed with the Select reset changes.

Unfortunately the Markup of the keyboard got mixed up a little and the XML you posted is incomplete.
What I can see in what is posted, that the Ampersand (&) is not correctly escaped to "&amp;amp;".
Does the file you try to import correctly parse here: https://xmlvalidation.com/ ? If it doesn't parse there, it will also not work on the app.
Also did you manually edit this XML file or was it solely generated by the app? Because the app should have escaped it (but maybe somehow didn't :().

**Comment by bigmutty** [comment]
It was only generated by the app. It failed to validate on that website either. That would explain why that error just started occurring. I just added that key. None of the other keyboard files escape the ampersand though.

**Comment by bigmutty** [comment]
Ok, the app doesn't escape the ampersand.

**Comment by Hizoul** [comment]
You are correct ShiftDownLabel where you were attempting to set the ampersand wasn't escaped bevore only the regular Label.
Furthermore the app now attempts to fix bad ampersands in the imported string.
Please let me know if these changes resolve your issue!

**Comment by bigmutty** [comment]
Yes, that fixed the problem.
